services:
- type: web
  name: The Butler
  env: static
  buildCommand: curl -LO https://cecil.app/cecil.phar && composer install && php cecil.phar build -v
  staticPublishPath: _site
  pullRequestPreviewsEnabled: true
