name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
env:
  INTL: 'no' # 'yes' if internationalization extensions are required
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: php:7.2-cli-alpine
    steps:
    - name: Install PHP extensions
      if: env.INTL == 'yes'
      run: |
        apk update
        apk add --no-cache gettext-dev icu-dev
        docker-php-ext-install -j$(nproc) gettext
        docker-php-ext-install -j$(nproc) intl
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install theme(s)
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --prefer-dist --no-dev --no-progress --no-interaction
    - name: Build site with Cecil
      env:
        CECIL_VERSION: '5.34.3'
        CECIL_BASEURL: '/'
      run: |
        if [[ -z "$CECIL_VERSION" ]]; then
          echo "### Downloading Cecil"
          curl -sSOL https://cecil.app/cecil.phar
        else
          echo "### Downloading Cecil $CECIL_VERSION"
          curl -sSOL https://cecil.app/download/$CECIL_VERSION/cecil.phar
        fi
        echo "### Building Cecil static site"
        php cecil.phar build -v
        echo "### Cecil Action done"
    - name: Upload site to Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: _site
        path: _site
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download site from Artifacts
      uses: actions/download-artifact@v1
      with:
        name: _site
    - name: Deploy site to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@2.0.1
      env:
        EMAIL: arnaud@ligny.org
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: _site
